// ─────────────────────────────────────────────────────────────
// Winchester TMMA Lookup — Data
// Members: as of January 7, 2026 (Google Drive roster)
// Streets: Winchester 2024 Street Index (supplemented from precinct maps)
// ─────────────────────────────────────────────────────────────

const TMMA_DATA = {
  dataAsOf: "January 7, 2026",

  // ── Members by precinct ──────────────────────────────────
  // Each member: { first, last, termEnds }
  members: {
    1: [
      { first: "Christa", last: "Anzalone-Russo", termEnds: 2026 },
      { first: "Anthea", last: "Brady", termEnds: 2028 },
      { first: "Shamus", last: "Brady", termEnds: 2027 },
      { first: "Prassede", last: "Calabi", termEnds: 2028 },
      { first: "Robert", last: "Deering", termEnds: 2027 },
      { first: "Kathleen", last: "Duncan", termEnds: 2027 },
      { first: "Hilary", last: "Eaton", termEnds: 2028 },
      { first: "Matthew", last: "Eaton", termEnds: 2028 },
      { first: "Joshua", last: "Ehrke", termEnds: 2028 },
      { first: "Mark", last: "Feblowitz", termEnds: 2027 },
      { first: "Marilyn", last: "Gagalis", termEnds: 2026 },
      { first: "Amanda", last: "Lewis", termEnds: 2026 },
      { first: "Douglas", last: "Marmon", termEnds: 2027 },
      { first: "Meredith", last: "Mason-Crowley", termEnds: 2026 },
      { first: "Timothy", last: "Matthews", termEnds: 2028 },
      { first: "Deborah", last: "Melkonian", termEnds: 2028 },
      { first: "Christian", last: "Nixon", termEnds: 2027 },
      { first: "Vincenzo", last: "Rascionato", termEnds: 2026 },
      { first: "Gregory", last: "Sawicki", termEnds: 2026 },
      { first: "Ann", last: "Sera", termEnds: 2026 },
      { first: "Eric", last: "Shediac", termEnds: 2028 },
      { first: "Maura", last: "Sullivan", termEnds: 2027 },
      { first: "Susan", last: "Verdicchio", termEnds: 2027 },
      { first: "Roger", last: "Wilson, Jr.", termEnds: 2026 }
    ],
    2: [
      { first: "Ryan", last: "Beck", termEnds: 2027 },
      { first: "Michelle", last: "Blumsack", termEnds: 2026 },
      { first: "Susan", last: "Carney", termEnds: 2027 },
      { first: "Laura", last: "Colella", termEnds: 2027 },
      { first: "Catherine", last: "Curtis", termEnds: 2028 },
      { first: "Jeffrey", last: "Dean", termEnds: 2028 },
      { first: "Michael", last: "Galvin", termEnds: 2026 },
      { first: "Soumya", last: "Ganapathy", termEnds: 2026 },
      { first: "Maciej", last: "Grzybek", termEnds: 2028 },
      { first: "Martha", last: "Hoyt", termEnds: 2028 },
      { first: "David", last: "Judelson", termEnds: 2026 },
      { first: "Benjamin", last: "Keeler", termEnds: 2026 },
      { first: "Deanna", last: "Laufer", termEnds: 2027 },
      { first: "Jian", last: "Liu", termEnds: 2028 },
      { first: "Jay", last: "Melkonian", termEnds: 2026 },
      { first: "Daniel", last: "Nakamoto", termEnds: 2027 },
      { first: "George", last: "Nowell", termEnds: 2027 },
      { first: "George", last: "Nowell, Jr.", termEnds: 2027 },
      { first: "Shukong", last: "Ou", termEnds: 2028 },
      { first: "Richard", last: "Rohan", termEnds: 2026 },
      { first: "Brian", last: "Sogoloff", termEnds: 2026 },
      { first: "Terence", last: "Tirella", termEnds: 2028 },
      { first: "Menina", last: "Widom", termEnds: 2027 },
      { first: "Stephanie", last: "Zaremba", termEnds: 2028 }
    ],
    3: [
      { first: "Hafiz", last: "Adamjee", termEnds: 2028 },
      { first: "Samantha", last: "Allison", termEnds: 2028 },
      { first: "Michelle", last: "Bergstrom", termEnds: 2026 },
      { first: "Kathleen", last: "Bodie", termEnds: 2027 },
      { first: "Janet", last: "Boswell", termEnds: 2028 },
      { first: "Caren", last: "Connelly", termEnds: 2027 },
      { first: "Vincent", last: "Dixon", termEnds: 2028 },
      { first: "Ruthie", last: "Gagne", termEnds: 2028 },
      { first: "Sarah", last: "Girotti", termEnds: 2028 },
      { first: "Joan", last: "Grenzeback", termEnds: 2026 },
      { first: "Lance", last: "Grenzeback", termEnds: 2026 },
      { first: "Lauren", last: "Herrmann", termEnds: 2027 },
      { first: "Thomas", last: "Howley", termEnds: 2027 },
      { first: "Elisa", last: "Jazan", termEnds: 2026 },
      { first: "Keri", last: "Layton", termEnds: 2026 },
      { first: "Jason", last: "Lewis", termEnds: 2027 },
      { first: "Susan", last: "Lewis", termEnds: 2026 },
      { first: "Heather", last: "Mango", termEnds: 2026 },
      { first: "William", last: "McGonigle", termEnds: 2028 },
      { first: "Susan", last: "McPhee", termEnds: 2027 },
      { first: "Susan", last: "Nardone", termEnds: 2028 },
      { first: "Amy", last: "Poftak", termEnds: 2027 },
      { first: "Gerard", last: "Sheehan", termEnds: 2026 },
      { first: "Robin", last: "Vos", termEnds: 2027 }
    ],
    4: [
      { first: "Stephen", last: "Boksanski", termEnds: 2027 },
      { first: "Aimee", last: "Burke", termEnds: 2028 },
      { first: "Jared", last: "Cumming", termEnds: 2026 },
      { first: "Eric", last: "Dimare", termEnds: 2028 },
      { first: "Stephen", last: "Engel", termEnds: 2026 },
      { first: "Patrick", last: "Hall", termEnds: 2028 },
      { first: "Ole-Petter", last: "Hamnvik", termEnds: 2028 },
      { first: "Brian", last: "McCarthy", termEnds: 2026 },
      { first: "Mary", last: "McIntyre", termEnds: 2027 },
      { first: "Caitlin", last: "Musto", termEnds: 2028 },
      { first: "Bettina", last: "Parks", termEnds: 2027 },
      { first: "Michelle", last: "Prior", termEnds: 2028 },
      { first: "Sally", last: "Quinn", termEnds: 2027 },
      { first: "Michael", last: "Rauseo", termEnds: 2027 },
      { first: "Heidi", last: "Rutstein DiLeo", termEnds: 2027 },
      { first: "Thomas", last: "Schrule", termEnds: 2026 },
      { first: "Susan", last: "Schwartz", termEnds: 2026 },
      { first: "Shannon", last: "Scott-Vernaglia", termEnds: 2028 },
      { first: "My Linh", last: "Truong", termEnds: 2026 },
      { first: "Bhavana", last: "Upadhyaya", termEnds: 2026 },
      { first: "Kathryn", last: "Valone", termEnds: 2027 },
      { first: "Candace", last: "Van Aken", termEnds: 2027 },
      { first: "Brian", last: "Vernaglia", termEnds: 2026 },
      { first: "Robin", last: "Wolf", termEnds: 2028 }
    ],
    5: [
      { first: "Charlene", last: "Band", termEnds: 2026 },
      { first: "William", last: "Band", termEnds: 2028 },
      { first: "Stefanida", last: "Blake", termEnds: 2028 },
      { first: "Christopher", last: "Centurelli", termEnds: 2028 },
      { first: "Peter", last: "Cheimets", termEnds: 2026 },
      { first: "Pamela", last: "Cort", termEnds: 2028 },
      { first: "Susan", last: "DeLeo", termEnds: 2028 },
      { first: "John", last: "Dobbins", termEnds: 2028 },
      { first: "Alan", last: "Field", termEnds: 2026 },
      { first: "Mariano", last: "Goluboff", termEnds: 2026 },
      { first: "Kathryn", last: "Hughes", termEnds: 2026 },
      { first: "Eric", last: "Keough", termEnds: 2027 },
      { first: "Stefanie", last: "Mnayarji", termEnds: 2026 },
      { first: "Helen", last: "Philliou", termEnds: 2028 },
      { first: "Craig", last: "Rabe", termEnds: 2027 },
      { first: "Jason", last: "Roeder", termEnds: 2027 },
      { first: "Carol", last: "Savage", termEnds: 2027 },
      { first: "I-Ching", last: "Scott", termEnds: 2026 },
      { first: "Colin", last: "Simson", termEnds: 2028 },
      { first: "John", last: "Snow, III", termEnds: 2026 },
      { first: "Caroline", last: "Staudt", termEnds: 2027 },
      { first: "William", last: "Swanton", termEnds: 2027 },
      { first: "Nicholas", last: "Troisi", termEnds: 2027 },
      { first: "Jacqueline", last: "Welch", termEnds: 2027 }
    ],
    6: [
      { first: "Michael", last: "Bettencourt", termEnds: 2026 },
      { first: "Steven", last: "Bonnell", termEnds: 2027 },
      { first: "Jonathan", last: "Cacciola", termEnds: 2026 },
      { first: "Jeffrey", last: "Calabrese", termEnds: 2026 },
      { first: "Andrew", last: "Clavette", termEnds: 2027 },
      { first: "Benjamin", last: "Coll", termEnds: 2028 },
      { first: "Tina", last: "Coll", termEnds: 2028 },
      { first: "Robert", last: "Colt", termEnds: 2026 },
      { first: "Anthony", last: "Cucinatti", termEnds: 2028 },
      { first: "Philip", last: "Frattaroli", termEnds: 2026 },
      { first: "Jack", last: "LeMenager", termEnds: 2028 },
      { first: "Nicole", last: "Lentine", termEnds: 2027 },
      { first: "Brenda", last: "Mandile", termEnds: 2027 },
      { first: "Karen", last: "Maruyama-Bolognese", termEnds: 2028 },
      { first: "Patrick", last: "Matteson", termEnds: 2026 },
      { first: "Joan", last: "Miller", termEnds: 2027 },
      { first: "John", last: "Miller", termEnds: 2028 },
      { first: "Richard", last: "Mucci", termEnds: 2026 },
      { first: "Kenneth", last: "Pruitt", termEnds: 2028 },
      { first: "Derek", last: "Ross", termEnds: 2027 },
      { first: "Monica", last: "Ross", termEnds: 2027 },
      { first: "Dorothy", last: "Simboli", termEnds: 2028 },
      { first: "Noha", last: "Soliman", termEnds: 2027 },
      { first: "Catherine", last: "Tomey", termEnds: 2026 }
    ],
    7: [
      { first: "Benjamin", last: "Albiani", termEnds: 2028 },
      { first: "Amy", last: "Beliveau", termEnds: 2028 },
      { first: "Joshua", last: "Bers", termEnds: 2027 },
      { first: "Megan", last: "Blackwell", termEnds: 2026 },
      { first: "Margaret", last: "Browder", termEnds: 2027 },
      { first: "Stephen", last: "Campbell", termEnds: 2026 },
      { first: "Steven", last: "Cucinatti", termEnds: 2028 },
      { first: "Deborah", last: "DePeter", termEnds: 2027 },
      { first: "Jennifer", last: "Haefeli", termEnds: 2026 },
      { first: "Thomas", last: "Hopcroft", termEnds: 2026 },
      { first: "Victoria", last: "Hopcroft", termEnds: 2027 },
      { first: "Leigh", last: "Hurd", termEnds: 2026 },
      { first: "Christopher", last: "Jones", termEnds: 2027 },
      { first: "Jean", last: "Jones", termEnds: 2026 },
      { first: "Lauren", last: "L'Esperance", termEnds: 2026 },
      { first: "Isobel", last: "Magee", termEnds: 2027 },
      { first: "Michelle", last: "McCarthy", termEnds: 2028 },
      { first: "William", last: "McPadden", termEnds: 2028 },
      { first: "Kara", last: "Nierenberg", termEnds: 2027 },
      { first: "Donnette", last: "Peltier", termEnds: 2028 },
      { first: "Brian", last: "Rowan", termEnds: 2026 },
      { first: "Elizabeth", last: "Schreiber", termEnds: 2027 },
      { first: "Ann", last: "Vaeth", termEnds: 2028 },
      { first: "Amy", last: "Wrenn", termEnds: 2028 }
    ],
    8: [
      { first: "Catherine", last: "Bauer", termEnds: 2026 },
      { first: "Paras", last: "Bhayani", termEnds: 2028 },
      { first: "Nicholas", last: "Bogovich", termEnds: 2028 },
      { first: "Edward", last: "Bopp", termEnds: 2028 },
      { first: "Donald", last: "Bradford", termEnds: 2026 },
      { first: "Wei", last: "Chen", termEnds: 2026 },
      { first: "Laura", last: "Conti", termEnds: 2027 },
      { first: "Michael", last: "Creane", termEnds: 2026 },
      { first: "Norman", last: "Doucette, Jr.", termEnds: 2027 },
      { first: "Erin", last: "Fogel", termEnds: 2027 },
      { first: "Russell", last: "Gay", termEnds: 2026 },
      { first: "Diab", last: "Jerius", termEnds: 2028 },
      { first: "Hank", last: "Lin", termEnds: 2027 },
      { first: "Martin", last: "Mahoney, II", termEnds: 2027 },
      { first: "Raegan", last: "McCain", termEnds: 2026 },
      { first: "Kathryn", last: "Mostow", termEnds: 2028 },
      { first: "Frieda", last: "Nace", termEnds: 2027 },
      { first: "Stacey", last: "Princi", termEnds: 2028 },
      { first: "Emily", last: "Shield", termEnds: 2028 },
      { first: "Steven", last: "Singer", termEnds: 2028 },
      { first: "Rebecca", last: "Slisz", termEnds: 2026 },
      { first: "Alison", last: "Swallow", termEnds: 2026 },
      { first: "Heather", last: "von Mering", termEnds: 2027 },
      { first: "John", last: "Wile", termEnds: 2027 }
    ]
  },

  // ── Street → Precinct(s) index ───────────────────────────
  // Sources: Winchester 2024 Street Index + precinct boundary maps
  // Streets spanning multiple precincts include all relevant ones.
  // For house-number disambiguation, see rangeRules below.
  streets: {
    "ABERJONA RD": [7],
    "ADAMS RD": [8],
    "AGAWAM RD": [5],
    "AINSWORTH RD": [1],
    "ALBAMONT RD": [5],
    "ALBEN ST": [1],
    "ALICE LN": [8],
    "ALLEN RD": [4],
    "AMBERWOOD DR": [6],
    "ANDREA CIR": [1],
    "ANDREWS RD": [6],
    "APPALACHIAN PKWY": [1],
    "AQUINAS RD": [7],
    "ARICIA LN": [5],
    "ARDLEY PL": [7],
    "ARISTOTLE RD": [7],
    "ARLINGTON ST": [5],
    "ARTHUR ST": [8],
    "ASH ST": [8],
    "AYER RD": [5],
    "AZALEA RD": [5],
    "BACON ST": [3, 4],
    "BACON RD": [3],
    "BALDPATE RD": [7],
    "BALDWIN ST": [8],
    "BATES ST": [2],
    "BELL ST": [1],
    "BELKNAP TER": [8],
    "BERKSHIRE RD": [5],
    "BIGELOW AVE": [6],
    "BIRCH LN": [5],
    "BLACK HORSE RD": [3],
    "BLOSSOM ST": [7],
    "BONAD RD": [1],
    "BORDER ST": [8],
    "BRADFORD RD": [8],
    "BRIARWOOD LN": [4],
    "BRIDGE ST": [2],
    "BROOK ST": [1],
    "BROOKSIDE AVE": [1],
    "BROOKSIDE PL": [1],
    "BROOKS ST": [4],
    "BUCK RD": [6],
    "BUSHCLIFF RD": [3],
    "CABOT ST": [7],
    "CAMBRIDGE ST": [5, 7],
    "CAMBRIDGE TER": [6],
    "CANAL ST": [8],
    "CANTERBURY RD": [4],
    "CAPRI TER": [6],
    "CARDINAL ST": [8],
    "CARR CIR": [6],
    "CARTER ST": [8],
    "CEDAR ST": [2],
    "CENTRAL ST": [3],
    "CHAPLIN ST": [8],
    "CHAPIN ST": [8],
    "CHARDON RD": [4],
    "CHARDWICK RD": [7],
    "CHESTER ST": [2],
    "CHESTNUT ST": [4],
    "CHISHOLM RD": [1],
    "CHURCH ST": [3, 7],
    "CIRCUIT AVE": [2],
    "CLARK ST": [8],
    "CLEMATIS ST": [1],
    "CLEARWATER RD": [4],
    "CLEVELAND ST": [8],
    "COBBLESTONE DR": [6],
    "COBBLESSTONE DR": [6],
    "COLLAMER RD": [8],
    "COLUMBIA RD": [6],
    "COLUMBUS AVE": [1],
    "CONANL LN": [1],
    "CONANT LN": [1],
    "COOLIDGE LN": [5],
    "COPLEY ST": [7],
    "CORT LN": [5],
    "COTTAGE RD": [3],
    "COUNTRY LN": [7],
    "COX RD": [5],
    "CRESCENT RD": [3],
    "CROSS ST": [1, 8],
    "CROFT RD": [3],
    "CRANSTON RD": [4],
    "D ST": [8],
    "DANA RD": [1],
    "DARTMOUTH ST": [7],
    "DAVEY ST": [1],
    "DAWES RD": [7],
    "DEAN RD": [1],
    "DIX ST": [3],
    "DIX TER": [3],
    "DOTHAN ST": [5],
    "DREXEL AVE": [5],
    "DUNHAM ST": [2],
    "DUNSTER DR": [5],
    "EATON CT": [2, 3],
    "EATON ST": [2, 3],
    "EDGEHILL RD": [4],
    "EDGEWATER RD": [4],
    "EDWARD DR": [5],
    "ELM ST": [2],
    "ELTON RD": [7],
    "ELMWOOD RD": [7],
    "EMERSON CT": [8],
    "EMERSON RD": [5],
    "ENGLEWOOD AVE": [1],
    "EUCALYPTUS RD": [1],
    "EUCLID RD": [1],
    "EUGENIA DR": [1],
    "EVERELL RD": [4],
    "EVERETT AVE": [5],
    "FAIRFIELD ST": [8],
    "FAIRLANE TER": [6],
    "FAIRVIEW TER": [4],
    "FARROW ST": [8],
    "FELLSDALE RD": [1],
    "FERNWAY": [3],
    "FENWICK RD": [4],
    "FIELDSTONE DR": [6],
    "FITZGERALD AVE": [8],
    "FLETCHER ST": [3],
    "FLORENCE ST": [2],
    "FOREST ST": [1],
    "FOREST CIR": [1],
    "FOXCROFT RD": [7],
    "FOX HUNT LN": [6],
    "FRANCIS AVE": [8],
    "FRANKLIN RD": [4],
    "GINN RD": [3],
    "GIRARD RD": [6],
    "GLEN AVE": [5],
    "GLENWOOD AVE": [8],
    "GODDARD ST": [3],
    "GOVERNORS AVE": [2],
    "GRASSMERE AVE": [3],
    "GRAYSON RD": [1],
    "GREEN ST": [3],
    "GROVE ST": [4],
    "GROVE PL": [4],
    "HANCOCK ST": [3],
    "HARRINGTON RD": [3],
    "HARRISON ST": [7],
    "HARVARD ST": [1, 2],
    "HAWTHORNE RD": [6],
    "HEMINGWAY ST": [8],
    "HENRY ST": [5],
    "HERRICK AVE": [4],
    "HIGH ST": [5],
    "HIGHLAND AVE": [1, 2, 4],
    "HIGHLAND VIEW AVE": [1],
    "HILLCREST PKWY": [1],
    "HILLCREST RD": [1],
    "HILL ST": [8],
    "HILLTOP RD": [8],
    "HILLSIDE TER": [1],
    "HINDS RD": [1],
    "HOLLAND ST": [2],
    "HOLLYWOOD RD": [4],
    "HORN RD": [3],
    "HORN POND BROOK RD": [8],
    "HUTCHINSON RD": [5],
    "INDIA RD": [7],
    "INDIAN HILL RD": [5],
    "INVERNESS AVE": [5],
    "IRVING ST": [1],
    "IVY CIR": [5],
    "JAMES RD": [5],
    "JEFFERSON AVE": [4],
    "JOHNSON RD": [5, 6],
    "KEITH RD": [7],
    "KENDALL ST": [2],
    "KENILWORTH RD": [1],
    "KENWIN RD": [1],
    "LAKE ST": [8],
    "LAKEVIEW RD": [5],
    "LAKEVIEW TER": [5],
    "LANTERN LN": [8],
    "LARAWY RD": [8],
    "LAUREL ST": [3],
    "LAWSON ST": [4],
    "LAWSON AVE": [4],
    "LAWRENCE ST": [7],
    "LEBANON ST": [1],
    "LEDGEWOOD RD": [8],
    "LEDYARD RD": [4],
    "LESLIE RD": [4],
    "LEWIS RD": [5],
    "LINCOLN RD": [2],
    "LINCOLN ST": [2],
    "LINDEN ST": [8],
    "LLOYD ST": [4],
    "LOCKE ST": [5],
    "LOCKELAND RD": [5],
    "LOCHWAN ST": [8],
    "LONGFELLOW RD": [7],
    "LORENA RD": [4],
    "LORING AVE": [8],
    "LOWELL ST": [1],
    "MADISON AVE": [4],
    "MAGNOLIA ST": [1],
    "MAIN ST": [3, 4],
    "MANCHESTER RD": [3],
    "MANOMET RD": [8],
    "MAPLE RD": [8],
    "MARC RD": [4],
    "MARGARET ST": [8],
    "MARION ST": [1],
    "MARSH RD": [3],
    "MARSHALL ST": [4],
    "MASON ST": [1],
    "MAXWELL RD": [7],
    "MAYFLOWER RD": [5],
    "MCCALL RD": [5],
    "MEADOWCROFT RD": [3],
    "MIDDLESEX ST": [8],
    "MOUNT OLIVE RD": [1],
    "MOUNT PLEASANT ST": [3],
    "MOUNT VERNON ST": [7],
    "MYOPIA CIR": [7],
    "MYRTLE ST": [3],
    "MYRTLE TER": [3],
    "MYSTIC AVE": [3],
    "MYSTIC VALLEY PKY": [3],
    "NASSAU DR": [6],
    "NATHANIEL RD": [1],
    "NELSON ST": [2],
    "NELSON AVE": [2],
    "NEW MEADOWS RD": [5],
    "NEWTON ST": [1],
    "NEWTON RD": [8],
    "NILES ST": [4],
    "NORFOLK RD": [7],
    "NORWOOD ST": [3],
    "NORTH BORDER RD": [1],
    "NORTH GATEWAY": [4],
    "OAK ST": [2],
    "OAKLAND RD": [4],
    "OLD SOUTH BORDER RD": [1],
    "ONEIDA RD": [7],
    "ONEIDA CIR": [7],
    "OVERLOOK WAY": [5],
    "OXFORD ST": [7],
    "PALMER ST": [3],
    "PARK AVE": [2],
    "PARK AVE EXT": [8],
    "PARKER RD": [8],
    "PARTRIDGE LN": [5],
    "PEPPER RD": [5],
    "PENN RD": [5],
    "PERKINS WAY": [4],
    "PICKERING ST": [8],
    "PILGRIM DR": [6],
    "PINE ST": [3],
    "PINE GROVE RD": [8],
    "PLATO RD": [7],
    "PLEASANT ST": [3],
    "PLYMOUTH RD": [5],
    "POCAHONTAS DR": [5],
    "PORTER ST": [3],
    "PRINCE AVE": [2],
    "PRISCILLA RD": [4],
    "POND ST": [8],
    "RANGELEY RD": [3],
    "RAVINE RD": [3],
    "RAVENS RD": [8],
    "RAYMOND PL": [8],
    "RESERVOIR RD": [1],
    "RICHARDSON ST": [8],
    "RIDGE RD": [5],
    "RIDGE ST": [5, 6],
    "RIDGEFIELD RD": [4],
    "RIDGEWAY RD": [7],
    "RISLEY RD": [4],
    "RIVER ST": [8],
    "ROBERTS RD": [5],
    "ROBINSON RD": [3],
    "ROBINSON ST": [3],
    "ROBINHOOD RD": [5],
    "ROCK AVE": [8],
    "ROCK HILL RD": [5],
    "ROYAL ST": [8],
    "ROYALSTON RD": [1],
    "RUMFORD ST": [8],
    "RUSSET LN": [6],
    "RUSSELL ST": [8],
    "SACHEM RD": [5],
    "SALISBURY ST": [7],
    "SALEM ST": [8],
    "SANBORN RD": [4],
    "SANBORN PL": [4],
    "SARGENT RD": [4],
    "SAWMILL BROOK RD": [1],
    "SAMOSET RD": [5],
    "SENECA RD": [7],
    "SHERIDAN CIR": [8],
    "SHEFFIELD RD": [4],
    "SHERWOOD RD": [4],
    "SIMONDS RD": [6],
    "SKILLINS RD": [8],
    "SKYLINE DR": [5],
    "SOCRATES WAY": [6],
    "SOUTH BORDER RD": [1],
    "SOUTH GATEWAY": [4],
    "SPRUCE ST": [2],
    "SQUIRE RD": [6],
    "STANDSISH RD": [4],
    "STANDISH RD": [4],
    "STONE AVE": [1],
    "STONEFIELD CIR": [6],
    "STOWELL RD": [4],
    "SUMMER ST": [2],
    "SUMMIT AVE": [3],
    "SUNSET RD": [1],
    "SURREY RD": [1],
    "SUSSEX RD": [4],
    "SWANTON ST": [2],
    "SYLVESTER AVE": [8],
    "SYLVESTER CT": [8],
    "SYMMES PL": [8],
    "TAFT DR": [5],
    "TANGLEWICK RD": [6],
    "THOMPSON ST": [7],
    "THOREAU LN": [6],
    "THORNBERRY RD": [6],
    "THOMAS MOORE RD": [6],
    "THORN ST": [6],
    "TRINITY RD": [5],
    "TUFTS ST": [2],
    "UPLAND RD": [8],
    "VALLEY ST": [1],
    "VINSON RD": [6],
    "VINE ST": [8],
    "WAINWRIGHT RD": [6],
    "WARE RD": [1],
    "WARWICK TER": [7],
    "WASHINGTON ST": [1, 3],
    "WATER ST": [8],
    "WATSON PL": [8],
    "WEDGEMERE AVE": [7],
    "WEDGE RD": [7],
    "WENDELL ST": [8],
    "WESTLAND AVE": [5, 6],
    "WESTLEY ST": [2],
    "WILDWOOD ST": [7],
    "WILDWOOD TER": [3],
    "WILLIAMS ST": [8],
    "WILLOWDALE RD": [4],
    "WILSON ST": [1],
    "WINCHEST RD": [7],
    "WINCHCREST DR": [6],
    "WINDEMERE RD": [5],
    "WINSLOW RD": [3],
    "WINTER ST": [2],
    "WINTHROP ST": [3],
    "WOLCOTT RD": [3],
    "WOODSIDE RD": [7],
    "WRIGHT ST": [6],
    "WYMAN AVE": [5],
    "YALE ST": [7],
    "YORK ST": [4]
  }
};
