// ─────────────────────────────────────────────────────────────
// Winchester TMMA Lookup — Data
// Members: as of January 7, 2026 (Google Drive roster)
// Streets: Winchester 2024 Public Book List PDF (tools/extract_streets.py)
//   417 streets extracted; 12 streets span multiple precincts.
// ─────────────────────────────────────────────────────────────

const TMMA_DATA = {
  dataAsOf: "January 7, 2026",

  // ── Members by precinct ──────────────────────────────────
  // Each member: { first, last, termEnds }
  members: {
    1: [
      { first: "Christa", last: "Anzalone-Russo", termEnds: 2026 },
      { first: "Anthea", last: "Brady", termEnds: 2028 },
      { first: "Shamus", last: "Brady", termEnds: 2027 },
      { first: "Prassede", last: "Calabi", termEnds: 2028 },
      { first: "Robert", last: "Deering", termEnds: 2027 },
      { first: "Kathleen", last: "Duncan", termEnds: 2027 },
      { first: "Hilary", last: "Eaton", termEnds: 2028 },
      { first: "Matthew", last: "Eaton", termEnds: 2028 },
      { first: "Joshua", last: "Ehrke", termEnds: 2028 },
      { first: "Mark", last: "Feblowitz", termEnds: 2027 },
      { first: "Marilyn", last: "Gagalis", termEnds: 2026 },
      { first: "Amanda", last: "Lewis", termEnds: 2026 },
      { first: "Douglas", last: "Marmon", termEnds: 2027 },
      { first: "Meredith", last: "Mason-Crowley", termEnds: 2026 },
      { first: "Timothy", last: "Matthews", termEnds: 2028 },
      { first: "Deborah", last: "Melkonian", termEnds: 2028 },
      { first: "Christian", last: "Nixon", termEnds: 2027 },
      { first: "Vincenzo", last: "Rascionato", termEnds: 2026 },
      { first: "Gregory", last: "Sawicki", termEnds: 2026 },
      { first: "Ann", last: "Sera", termEnds: 2026 },
      { first: "Eric", last: "Shediac", termEnds: 2028 },
      { first: "Maura", last: "Sullivan", termEnds: 2027 },
      { first: "Susan", last: "Verdicchio", termEnds: 2027 },
      { first: "Roger", last: "Wilson, Jr.", termEnds: 2026 }
    ],
    2: [
      { first: "Ryan", last: "Beck", termEnds: 2027 },
      { first: "Michelle", last: "Blumsack", termEnds: 2026 },
      { first: "Susan", last: "Carney", termEnds: 2027 },
      { first: "Laura", last: "Colella", termEnds: 2027 },
      { first: "Catherine", last: "Curtis", termEnds: 2028 },
      { first: "Jeffrey", last: "Dean", termEnds: 2028 },
      { first: "Michael", last: "Galvin", termEnds: 2026 },
      { first: "Soumya", last: "Ganapathy", termEnds: 2026 },
      { first: "Maciej", last: "Grzybek", termEnds: 2028 },
      { first: "Martha", last: "Hoyt", termEnds: 2028 },
      { first: "David", last: "Judelson", termEnds: 2026 },
      { first: "Benjamin", last: "Keeler", termEnds: 2026 },
      { first: "Deanna", last: "Laufer", termEnds: 2027 },
      { first: "Jian", last: "Liu", termEnds: 2028 },
      { first: "Jay", last: "Melkonian", termEnds: 2026 },
      { first: "Daniel", last: "Nakamoto", termEnds: 2027 },
      { first: "George", last: "Nowell", termEnds: 2027 },
      { first: "George", last: "Nowell, Jr.", termEnds: 2027 },
      { first: "Shukong", last: "Ou", termEnds: 2028 },
      { first: "Richard", last: "Rohan", termEnds: 2026 },
      { first: "Brian", last: "Sogoloff", termEnds: 2026 },
      { first: "Terence", last: "Tirella", termEnds: 2028 },
      { first: "Menina", last: "Widom", termEnds: 2027 },
      { first: "Stephanie", last: "Zaremba", termEnds: 2028 }
    ],
    3: [
      { first: "Hafiz", last: "Adamjee", termEnds: 2028 },
      { first: "Samantha", last: "Allison", termEnds: 2028 },
      { first: "Michelle", last: "Bergstrom", termEnds: 2026 },
      { first: "Kathleen", last: "Bodie", termEnds: 2027 },
      { first: "Janet", last: "Boswell", termEnds: 2028 },
      { first: "Caren", last: "Connelly", termEnds: 2027 },
      { first: "Vincent", last: "Dixon", termEnds: 2028 },
      { first: "Ruthie", last: "Gagne", termEnds: 2028 },
      { first: "Sarah", last: "Girotti", termEnds: 2028 },
      { first: "Joan", last: "Grenzeback", termEnds: 2026 },
      { first: "Lance", last: "Grenzeback", termEnds: 2026 },
      { first: "Lauren", last: "Herrmann", termEnds: 2027 },
      { first: "Thomas", last: "Howley", termEnds: 2027 },
      { first: "Elisa", last: "Jazan", termEnds: 2026 },
      { first: "Keri", last: "Layton", termEnds: 2026 },
      { first: "Jason", last: "Lewis", termEnds: 2027 },
      { first: "Susan", last: "Lewis", termEnds: 2026 },
      { first: "Heather", last: "Mango", termEnds: 2026 },
      { first: "William", last: "McGonigle", termEnds: 2028 },
      { first: "Susan", last: "McPhee", termEnds: 2027 },
      { first: "Susan", last: "Nardone", termEnds: 2028 },
      { first: "Amy", last: "Poftak", termEnds: 2027 },
      { first: "Gerard", last: "Sheehan", termEnds: 2026 },
      { first: "Robin", last: "Vos", termEnds: 2027 }
    ],
    4: [
      { first: "Stephen", last: "Boksanski", termEnds: 2027 },
      { first: "Aimee", last: "Burke", termEnds: 2028 },
      { first: "Jared", last: "Cumming", termEnds: 2026 },
      { first: "Eric", last: "Dimare", termEnds: 2028 },
      { first: "Stephen", last: "Engel", termEnds: 2026 },
      { first: "Patrick", last: "Hall", termEnds: 2028 },
      { first: "Ole-Petter", last: "Hamnvik", termEnds: 2028 },
      { first: "Brian", last: "McCarthy", termEnds: 2026 },
      { first: "Mary", last: "McIntyre", termEnds: 2027 },
      { first: "Caitlin", last: "Musto", termEnds: 2028 },
      { first: "Bettina", last: "Parks", termEnds: 2027 },
      { first: "Michelle", last: "Prior", termEnds: 2028 },
      { first: "Sally", last: "Quinn", termEnds: 2027 },
      { first: "Michael", last: "Rauseo", termEnds: 2027 },
      { first: "Heidi", last: "Rutstein DiLeo", termEnds: 2027 },
      { first: "Thomas", last: "Schrule", termEnds: 2026 },
      { first: "Susan", last: "Schwartz", termEnds: 2026 },
      { first: "Shannon", last: "Scott-Vernaglia", termEnds: 2028 },
      { first: "My Linh", last: "Truong", termEnds: 2026 },
      { first: "Bhavana", last: "Upadhyaya", termEnds: 2026 },
      { first: "Kathryn", last: "Valone", termEnds: 2027 },
      { first: "Candace", last: "Van Aken", termEnds: 2027 },
      { first: "Brian", last: "Vernaglia", termEnds: 2026 },
      { first: "Robin", last: "Wolf", termEnds: 2028 }
    ],
    5: [
      { first: "Charlene", last: "Band", termEnds: 2026 },
      { first: "William", last: "Band", termEnds: 2028 },
      { first: "Stefanida", last: "Blake", termEnds: 2028 },
      { first: "Christopher", last: "Centurelli", termEnds: 2028 },
      { first: "Peter", last: "Cheimets", termEnds: 2026 },
      { first: "Pamela", last: "Cort", termEnds: 2028 },
      { first: "Susan", last: "DeLeo", termEnds: 2028 },
      { first: "John", last: "Dobbins", termEnds: 2028 },
      { first: "Alan", last: "Field", termEnds: 2026 },
      { first: "Mariano", last: "Goluboff", termEnds: 2026 },
      { first: "Kathryn", last: "Hughes", termEnds: 2026 },
      { first: "Eric", last: "Keough", termEnds: 2027 },
      { first: "Stefanie", last: "Mnayarji", termEnds: 2026 },
      { first: "Helen", last: "Philliou", termEnds: 2028 },
      { first: "Craig", last: "Rabe", termEnds: 2027 },
      { first: "Jason", last: "Roeder", termEnds: 2027 },
      { first: "Carol", last: "Savage", termEnds: 2027 },
      { first: "I-Ching", last: "Scott", termEnds: 2026 },
      { first: "Colin", last: "Simson", termEnds: 2028 },
      { first: "John", last: "Snow, III", termEnds: 2026 },
      { first: "Caroline", last: "Staudt", termEnds: 2027 },
      { first: "William", last: "Swanton", termEnds: 2027 },
      { first: "Nicholas", last: "Troisi", termEnds: 2027 },
      { first: "Jacqueline", last: "Welch", termEnds: 2027 }
    ],
    6: [
      { first: "Michael", last: "Bettencourt", termEnds: 2026 },
      { first: "Steven", last: "Bonnell", termEnds: 2027 },
      { first: "Jonathan", last: "Cacciola", termEnds: 2026 },
      { first: "Jeffrey", last: "Calabrese", termEnds: 2026 },
      { first: "Andrew", last: "Clavette", termEnds: 2027 },
      { first: "Benjamin", last: "Coll", termEnds: 2028 },
      { first: "Tina", last: "Coll", termEnds: 2028 },
      { first: "Robert", last: "Colt", termEnds: 2026 },
      { first: "Anthony", last: "Cucinatti", termEnds: 2028 },
      { first: "Philip", last: "Frattaroli", termEnds: 2026 },
      { first: "Jack", last: "LeMenager", termEnds: 2028 },
      { first: "Nicole", last: "Lentine", termEnds: 2027 },
      { first: "Brenda", last: "Mandile", termEnds: 2027 },
      { first: "Karen", last: "Maruyama-Bolognese", termEnds: 2028 },
      { first: "Patrick", last: "Matteson", termEnds: 2026 },
      { first: "Joan", last: "Miller", termEnds: 2027 },
      { first: "John", last: "Miller", termEnds: 2028 },
      { first: "Richard", last: "Mucci", termEnds: 2026 },
      { first: "Kenneth", last: "Pruitt", termEnds: 2028 },
      { first: "Derek", last: "Ross", termEnds: 2027 },
      { first: "Monica", last: "Ross", termEnds: 2027 },
      { first: "Dorothy", last: "Simboli", termEnds: 2028 },
      { first: "Noha", last: "Soliman", termEnds: 2027 },
      { first: "Catherine", last: "Tomey", termEnds: 2026 }
    ],
    7: [
      { first: "Benjamin", last: "Albiani", termEnds: 2028 },
      { first: "Amy", last: "Beliveau", termEnds: 2028 },
      { first: "Joshua", last: "Bers", termEnds: 2027 },
      { first: "Megan", last: "Blackwell", termEnds: 2026 },
      { first: "Margaret", last: "Browder", termEnds: 2027 },
      { first: "Stephen", last: "Campbell", termEnds: 2026 },
      { first: "Steven", last: "Cucinatti", termEnds: 2028 },
      { first: "Deborah", last: "DePeter", termEnds: 2027 },
      { first: "Jennifer", last: "Haefeli", termEnds: 2026 },
      { first: "Thomas", last: "Hopcroft", termEnds: 2026 },
      { first: "Victoria", last: "Hopcroft", termEnds: 2027 },
      { first: "Leigh", last: "Hurd", termEnds: 2026 },
      { first: "Christopher", last: "Jones", termEnds: 2027 },
      { first: "Jean", last: "Jones", termEnds: 2026 },
      { first: "Lauren", last: "L'Esperance", termEnds: 2026 },
      { first: "Isobel", last: "Magee", termEnds: 2027 },
      { first: "Michelle", last: "McCarthy", termEnds: 2028 },
      { first: "William", last: "McPadden", termEnds: 2028 },
      { first: "Kara", last: "Nierenberg", termEnds: 2027 },
      { first: "Donnette", last: "Peltier", termEnds: 2028 },
      { first: "Brian", last: "Rowan", termEnds: 2026 },
      { first: "Elizabeth", last: "Schreiber", termEnds: 2027 },
      { first: "Ann", last: "Vaeth", termEnds: 2028 },
      { first: "Amy", last: "Wrenn", termEnds: 2028 }
    ],
    8: [
      { first: "Catherine", last: "Bauer", termEnds: 2026 },
      { first: "Paras", last: "Bhayani", termEnds: 2028 },
      { first: "Nicholas", last: "Bogovich", termEnds: 2028 },
      { first: "Edward", last: "Bopp", termEnds: 2028 },
      { first: "Donald", last: "Bradford", termEnds: 2026 },
      { first: "Wei", last: "Chen", termEnds: 2026 },
      { first: "Laura", last: "Conti", termEnds: 2027 },
      { first: "Michael", last: "Creane", termEnds: 2026 },
      { first: "Norman", last: "Doucette, Jr.", termEnds: 2027 },
      { first: "Erin", last: "Fogel", termEnds: 2027 },
      { first: "Russell", last: "Gay", termEnds: 2026 },
      { first: "Diab", last: "Jerius", termEnds: 2028 },
      { first: "Hank", last: "Lin", termEnds: 2027 },
      { first: "Martin", last: "Mahoney, II", termEnds: 2027 },
      { first: "Raegan", last: "McCain", termEnds: 2026 },
      { first: "Kathryn", last: "Mostow", termEnds: 2028 },
      { first: "Frieda", last: "Nace", termEnds: 2027 },
      { first: "Stacey", last: "Princi", termEnds: 2028 },
      { first: "Emily", last: "Shield", termEnds: 2028 },
      { first: "Steven", last: "Singer", termEnds: 2028 },
      { first: "Rebecca", last: "Slisz", termEnds: 2026 },
      { first: "Alison", last: "Swallow", termEnds: 2026 },
      { first: "Heather", last: "von Mering", termEnds: 2027 },
      { first: "John", last: "Wile", termEnds: 2027 }
    ]
  },

  // ── Street → Precinct(s) index ───────────────────────────
  // Source: Winchester 2024 Public Book List PDF (via tools/extract_streets.py)
  // Streets with multiple precincts span precinct boundaries; house numbers
  // don't map cleanly by range (boundary is irregular/side-of-street).
  // For those streets, users will be shown all matching precincts.
  streets: {
    "ADAMS RD": [8],
    "AGAWAM RD": [5],
    "AINSWORTH RD": [1],
    "ALBAMONT RD": [5],
    "ALBEN ST": [1],
    "ALDEN LN": [4],
    "ALESWORTH AVE": [7],
    "ALICE LN": [3],
    "ALLEN RD": [4],
    "AMBERWOOD DR": [6],
    "ANDREA CIR": [1],
    "ANDREWS RD": [5],
    "APPALACHIAN RD": [1],
    "AQUINAS PATH": [6],
    "ARBOR LN": [8],
    "ARDLEY PL": [7],
    "ARDLEY RD": [7],
    "ARICIA LN": [6],
    "ARISTOTLE DR": [6],
    "ARLINGTON ST": [5],
    "ARTHUR ST": [8],
    "ATHERTON RD": [6],
    "AZALEA RD": [6],
    "BACON ST": [3, 4],
    "BALDWIN ST": [8],
    "BATES RD": [1],
    "BELKNAP TER": [8],
    "BELLEVUE AVE": [1],
    "BERKSHIRE DR": [6],
    "BIGELOW AVE": [6],
    "BIRCH LN": [6],
    "BLACK HORSE TER": [3],
    "BLOSSOM HILL RD": [5],
    "BONAD RD": [1],
    "BORDER ST": [8],
    "BRADFORD RD": [8],
    "BRANTWOOD RD": [7],
    "BRIARWOOD LN": [4],
    "BRIDGE ST": [3],
    "BROOKS ST": [4],
    "BROOKSIDE AVE": [1],
    "BRUCE RD": [4],
    "BUCKMAN DR": [6],
    "BUSHCLIFF TER": [2],
    "CABOT ST": [7],
    "CALUMET RD": [7],
    "CAMBRIDGE ST": [5, 7],
    "CANAL ST": [8],
    "CANTERBURY RD": [4],
    "CAPRI TER": [6],
    "CARDINAL ST": [1],
    "CARRIAGE LN": [6],
    "CARTER ST": [8],
    "CEDAR ST": [2],
    "CENTRAL GRN": [3],
    "CENTRAL ST": [3],
    "CHAPIN CT": [2],
    "CHAPIN ST": [2],
    "CHARDON RD": [4],
    "CHARLES RD": [8],
    "CHESTER ST": [2],
    "CHESTERFORD RD": [7],
    "CHESTERFORD TER": [7],
    "CHESTNUT ST": [4],
    "CHISHOLM RD": [1],
    "CHURCH ST": [7],
    "CHURCHILL CIR": [1],
    "CHURCHILL RD": [1],
    "CLARK ST": [8],
    "CLEARWATER RD": [4],
    "CLEMATIS ST": [1],
    "CLEVELAND RD": [8],
    "CLIFF ST": [3],
    "COBBLESTONE DR": [8],
    "COLLAMORE ST": [1],
    "COLUMBUS RD": [2],
    "CONANT RD": [2],
    "COOLIDGE RD": [6],
    "COPLEY ST": [7],
    "COTTAGE AVE": [7],
    "COUNTRY LN": [5],
    "COX RD": [6],
    "CRANSTON RD": [4],
    "CRESCENT RD": [3],
    "CROSS ST": [1, 8],
    "CURTIS CIR": [3],
    "CURTIS ST": [3],
    "CUTTING ST": [3],
    "D ST": [1],
    "DANA AVE": [1],
    "DARTMOUTH ST": [7],
    "DAVEY LN": [3],
    "DAWES AVE": [6],
    "DEAN RD": [1],
    "DENNETT RD": [4],
    "DIX ST": [3],
    "DIX TER": [3],
    "DOTHAN ST": [5],
    "DREXEL AVE": [7],
    "DUNHAM ST": [2],
    "DUNSTER LN": [5],
    "EAST ST": [8],
    "EATON CT": [2],
    "EATON ST": [2, 3],
    "EDGEHILL RD": [4],
    "EDGEWATER PL": [5],
    "EDWARD DR": [5],
    "ELM ST": [3],
    "ELMWOOD AVE": [3],
    "EMERSON CT": [2],
    "EMERSON RD": [5],
    "ENGLEWOOD RD": [1],
    "EUCLID AVE": [1],
    "EUGENE DR": [1],
    "EVERELL RD": [4],
    "EVERETT AVE": [7],
    "FAIRFIELD PL": [8],
    "FAIRLANE TER": [6],
    "FAIRMOUNT ST": [1],
    "FAIRVIEW TER": [3],
    "FARROW ST": [8],
    "FELLS RD": [1],
    "FELSDALE CLOSE": [4],
    "FENWICK RD": [4],
    "FERNWAY": [5],
    "FERNWAY TER": [5],
    "FIELDSTONE DR": [6],
    "FITZGERALD AVE": [8],
    "FLETCHER ST": [7],
    "FLORENCE ST": [2],
    "FOREST CIR": [1],
    "FOREST ST": [1],
    "FOX HUNT LN": [5],
    "FOXCROFT RD": [7],
    "FRANCIS CIRCUIT": [3],
    "FRANKLIN RD": [4],
    "GARDNER PL": [7],
    "GARFIELD AVE": [1],
    "GEORGE RD": [8],
    "GERSHON WAY": [6],
    "GINN RD": [3],
    "GIRARD RD": [5],
    "GLEN GRN": [7],
    "GLEN RD": [7],
    "GLENGARRY": [3],
    "GLENWOOD AVE": [8],
    "GODDU AVE": [4],
    "GOVERNORS AVE": [2],
    "GRANT RD": [1],
    "GRASSMERE AVE": [3],
    "GRAYSON RD": [1],
    "GRAYSTONE CIR": [7],
    "GREELEY RD": [3],
    "GROVE PL": [4],
    "GROVE ST": [4],
    "HANCOCK ST": [2],
    "HARRINGTON RD": [7],
    "HARRISON ST": [7],
    "HARVARD ST": [1],
    "HASTINGS RD": [4],
    "HAWTHORNE RD": [6],
    "HEMINGWAY ST": [8],
    "HENRY ST": [5],
    "HERRICK ST": [4],
    "HIGH ST": [5],
    "HIGHLAND AVE": [1, 3],
    "HIGHLAND TER": [1],
    "HIGHLAND VIEW AV": [8],
    "HILL ST": [8],
    "HILLCREST PKY": [1],
    "HILLSIDE AVE": [3],
    "HILLTOP RD": [6],
    "HINDS RD": [1],
    "HOLLAND ST": [2],
    "HOLLYWOOD RD": [4],
    "HOLTON ST": [8],
    "HORN POND BROOK": [8],
    "HUTCHINSON RD": [5],
    "INDIAN HILL RD": [5],
    "INVERNESS RD": [7],
    "IRVING ST": [1],
    "IVY CIR": [7],
    "JAMES ST": [5],
    "JEFFERSON RD": [4],
    "JOHNSON RD": [6],
    "KEENAN DR": [1],
    "KENDALL ST": [3],
    "KENILWORTH RD": [1],
    "KENWIN RD": [1],
    "KIRK ST": [8],
    "LAGRANGE ST": [7],
    "LAKE ST": [3, 8],
    "LAKEVIEW RD": [5],
    "LAKEVIEW TER": [5],
    "LANTERN LN": [3],
    "LAUREL HILL LN": [1],
    "LAUREL ST": [7],
    "LAWRENCE ST": [7],
    "LAWSON RD": [4],
    "LEBANON ST": [1],
    "LEDGEWOOD RD": [3],
    "LEDYARD RD": [4],
    "LESLIE RD": [4],
    "LEWIS RD": [7],
    "LINCOLN ST": [2],
    "LINCOLNSHIRE WAY": [3],
    "LINDEN ST": [8],
    "LLOYD ST": [3],
    "LOCHWAN ST": [8],
    "LOCKE ST": [5],
    "LOCKELAND RD": [5],
    "LONGFELLOW RD": [6],
    "LORENA RD": [4],
    "LORING AVE": [8],
    "LORING CT": [8],
    "MADISON AVE": [4],
    "MADISON AVE W": [3],
    "MAGNOLIA WAY": [1],
    "MAIN ST": [3, 4],
    "MANCHESTER RD": [3],
    "MANOMET RD": [5],
    "MAPLE RD": [1],
    "MARCHANT RD": [4],
    "MARION ST": [1],
    "MARSHALL RD": [4],
    "MASON ST": [3],
    "MAXWELL RD": [3],
    "MAYFLOWER RD": [5],
    "MCCALL RD": [5],
    "MEADOWCROFT RD": [3],
    "MERIDEN RD": [4],
    "MIDDLESEX ST": [7],
    "MT PLEASANT ST": [3],
    "MT VERNON ST": [3],
    "MYOPIA RD": [5],
    "MYRTLE ST": [3],
    "MYRTLE TER": [3],
    "MYSTIC AVE": [3],
    "MYSTIC VALLEY PKY": [3, 5],
    "NASSAU DR": [6],
    "NATHANIEL RD": [1],
    "NELSON ST": [2],
    "NEW MEADOWS RD": [5],
    "NEWTON ST": [8],
    "NILES LN": [5],
    "NORFOLK RD": [7],
    "NORTH BORDER RD": [1],
    "NORTH GATEWAY": [4],
    "NORWOOD ST": [3],
    "OAK ST": [2],
    "OAKLAND CIR": [4],
    "OLD OAK LN": [3],
    "OLDE LYME RD": [6],
    "OLDE VILLAGE DR": [6],
    "OLIVE ST": [2],
    "ONEIDA CIR": [5],
    "ONEIDA RD": [5],
    "ORIENT ST": [1],
    "OVERLOOK WAY": [5],
    "OX PASTURE": [4],
    "OXFORD ST": [7],
    "PALMER ST": [7],
    "PARK AVE": [2],
    "PARK RD": [2],
    "PARK ST": [3],
    "PARKER RD": [7],
    "PARTRIDGE LN": [6],
    "PENN RD": [5],
    "PEPPER HILL DR": [5],
    "PERKINS RD": [4],
    "PICKERING ST": [8],
    "PIERREPONT RD": [4],
    "PILGRIM DR": [6],
    "PINE GROVE PARK": [8],
    "PINE ST": [3],
    "PLATO TER": [6],
    "PLYMOUTH RD": [5],
    "POCAHONTAS DR": [5],
    "POLK RD": [1],
    "POND ST": [7],
    "PORTER ST": [8],
    "PRINCE AVE": [2],
    "PRISCILLA LN": [4],
    "PROSPECT ST": [3],
    "QUIGLEY CT": [2],
    "RANGELEY RD": [3],
    "RANGELEY RIDGE": [3],
    "RAVENSCROFT RD": [5],
    "RAVINE RD": [3],
    "RAYMOND PL": [2],
    "RED COACH LN": [6],
    "RESERVOIR ST": [1],
    "RICHARDSON ST": [8],
    "RIDGE ST": [5, 6],
    "RIDGEFIELD RD": [4],
    "RIDGEWAY": [2],
    "RISLEY RD": [4],
    "RIVER ST": [2],
    "ROBERTS RD": [6],
    "ROBINHOOD RD": [5, 6],
    "ROBINSON CIR": [5],
    "ROBINSON PARK": [5],
    "ROCK AVE": [8],
    "ROCKY LEDGE TER": [6],
    "ROYAL ST": [8],
    "ROYALSTON AVE": [1],
    "RUMFORD ST": [8],
    "RUSSELL RD": [8],
    "RUSSET LN": [6],
    "SACHEM RD": [5],
    "SALEM ST": [8],
    "SALISBURY ST": [7],
    "SAMOSET RD": [5],
    "SANBORN PL": [4],
    "SANBORN ST": [4],
    "SARGENT RD": [4],
    "SAWMILL BROOK RD": [1],
    "SCHOOL ST": [3],
    "SENECA RD": [5],
    "SHEFFIELD RD": [7],
    "SHEFFIELD WEST": [7],
    "SHEPARD CT": [8],
    "SHERIDAN CIR": [8],
    "SHERMAN PL": [8],
    "SHERWOOD RD": [4],
    "SHORE RD": [2],
    "SIMONDS RD": [6],
    "SKILLINGS RD": [2],
    "SKY LINE DR": [5],
    "SOCRATES WAY": [6],
    "SOUTH BORDER RD": [4],
    "SOUTH GATEWAY": [4],
    "SPRUCE ST": [2],
    "SQUANTO RD": [5],
    "SQUIRE RD": [6],
    "ST AUGUSTINE CT": [6],
    "ST THOMAS MORE D": [6],
    "STANDISH LN": [4],
    "STEVENS ST": [3],
    "STONE AVE": [1],
    "STONEFIELD CIR": [5],
    "STOWELL RD": [4],
    "STRATFORD RD": [7],
    "SUMMER ST": [2],
    "SUMMIT AVE": [3],
    "SUNSET RD": [1],
    "SURREY RD": [6],
    "SUSSEX RD": [4],
    "SWAN RD": [5],
    "SWANTON ST": [2, 8],
    "SYLVESTER AVE": [8],
    "SYLVESTER CT": [8],
    "SYMMES RD": [3],
    "TAFT CIR": [5],
    "TAFT DR": [5],
    "TANGLEWOOD LN": [6],
    "TANIA CIR": [6],
    "THOMPSON ST": [3],
    "THOREAU CIR": [5],
    "THORNBERRY RD": [6],
    "THORNTON RD": [5],
    "TOWN WAY": [4],
    "TREMONT ST": [2],
    "TRINITY RD": [5],
    "TUFTS RD": [1],
    "UPLAND RD": [8],
    "VALLEY RD": [1],
    "VALLEYWOOD CIR": [6],
    "VERPLAST AVE": [8],
    "VIKING RD": [5],
    "VINE ST": [3],
    "VINSON CIR": [6],
    "WAGON WHEEL RD": [6],
    "WAINWRIGHT RD": [6],
    "WALNUT ST": [3],
    "WARE RD": [1],
    "WARREN ST": [7],
    "WASHINGTON ST": [1, 2, 3],
    "WATER ST": [8],
    "WATSON PL": [8],
    "WEBSTER ST": [2],
    "WEDGE POND RD": [3],
    "WEDGEMERE AVE": [7],
    "WELLINGTON RD": [4],
    "WENDELL ST": [8],
    "WEST CHARDON RD": [4],
    "WESTGATE RD": [6],
    "WESTLAND AVE": [5],
    "WESTLEY ST": [2],
    "WHITE ST": [8],
    "WICKFORD RD": [7],
    "WICKHAM RD": [4],
    "WILDWOOD ST": [7],
    "WILDWOOD TER": [7],
    "WILLIAMS CIR": [8],
    "WILLOW ST": [3],
    "WILLOWDALE RD": [4],
    "WILSON ST": [1],
    "WINCHESTER PL": [3],
    "WINCHESTER TER": [3],
    "WINCREST DR": [6],
    "WINDEMERE RD": [6],
    "WINDSONG LN": [6],
    "WINFORD WAY": [4],
    "WINSLOW RD": [3],
    "WINTER ST": [2],
    "WINTHROP ST": [3],
    "WINTHROP ST EXT": [3],
    "WOLCOTT RD": [2],
    "WOLCOTT TER": [2],
    "WOOD LN": [5],
    "WOODSIDE RD": [7],
    "WORTHEN RD": [6],
    "WRIGHT ST": [5],
    "WYMAN CT": [7],
    "YALE ST": [7],
    "YORK RD": [4],
  }
};